//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linguispark.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMusteri
    {
        public int id { get; set; }
        public Nullable<int> musteriAdSoyad { get; set; }
        public string musteriAdres { get; set; }
        public Nullable<bool> musteriDurum { get; set; }
    
        public virtual tblSatis tblSatis { get; set; }
    }
}
