//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linguispark.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSatis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSatis()
        {
            this.tblMusteri = new HashSet<tblMusteri>();
        }
    
        public int id { get; set; }
        public Nullable<int> cevirmen { get; set; }
        public string musteriAdSoyad { get; set; }
        public Nullable<int> fiyat { get; set; }
        public string Mail { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tblCevirmen tblCevirmen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMusteri> tblMusteri { get; set; }
    }
}
